### PR TITLE
Fixes library warnings. Switched to feather

### PR DESCRIPTION
**Pull request by mschrader15**
Hi @pwr-inf,

Thanks for open sourcing this great project & paper! We have been working with a modified version (https://github.com/green-last-mile/hex2vec) but recently wanted to compare against your paper's embeddings. 

Like #1 we ran into OSM download size issues (especially with pickle), as well as library version issues, etc. This PR fixes the issues we have up until running `notebooks/cluster-word2vec.ipynb`

### CODE REVIEW

**Comment by simonusher** [comment]
Hi, @mschrader15. First of all, thank you very much for taking your time and contributing the fixes.
I know the code isn't perfect, especially the data downloading/wrangling parts. I'm glad you liked the paper and that you're using the code. I'm sorry nobody replied to you earlier, but we're no longer actively maintaining this repository. I'll make sure to add this information to the readme in the following days.
As for the PR, the changes look good so I'll merge them. Thank you once again for contributing.

**Comment by simonusher** [comment]
As a side note, we're currently working on a new project that is meant to bring our team's work together, as a general-use library for spatial embeddings. It's still a WIP, but we should hopefully be releasing an early version in the upcoming months. You can find it here: [https://github.com/srai-lab/srai](https://github.com/srai-lab/srai). If you're interested in this topic, feel free to take a look. Maybe it will prove useful in the future.
In the meantime you might want to take a look at our other papers that tackle different data: [roads](https://calychas.github.io/osm-road-infrastructure/), [gtfs public transport timetables](https://github.com/pwr-inf/gtfs2vec) or tasks: [bike sharing station location prediction](https://github.com/pwr-inf/Transfer-learning-approach-to-bicycle-sharing-systems-station-location-planning-using-OpenStreetMap)

**Comment by mschrader15** [comment]
No problem @simonusher! Thanks for sharing the **srai** and the papers. I will look into those.

As you might be interested, we are using your proposed spatial embeddings & h3 microregions to model parcel delivery service times in various cities. We should be finishing up a paper soon that I will share!

**Comment by simonusher** [comment]
Sounds great. Can't wait to read it and see how it works 😄

**Pull request merged**
